// lib/apply-script.js — 生成目标机自安装脚本(apply.ps1 + apply.sh)。
// 设计要点:
// 1) 不依赖 dsh-sync 插件(解决引导悖论):目标机只有 dsh + node + pnpm 也能跑。
// 2) ps1 / sh 从同一份 plan 渲染,避免两套脚本行为漂移。
// 3) apply 是半破坏性操作,必须带安全网:先备份,任一步失败自动回滚。
// 4) profile 声明文件(cordis.patch.yml / .npmrc / pnpm-workspace.yaml)在 plugin add
//    之前落地 —— pnpm-workspace.yaml 的 allowBuilds 正是 git 依赖能否构建通过的关键。

/**
 * 由 manifest 推导 apply 计划,两种脚本共用,保证行为一致。
 * @param {object} m manifest
 */
export function buildApplyPlan(m) {
  const profiles = (m.profiles || []).map((p) => ({
    name: p.name,
    profileFiles: p.profileFiles || [],
    // 判定顺序很重要:先查依赖表,再谈"是不是内置包"。
    // 常见情形:把自己开发的插件也命名为 @deepseek-ai/<name>(本地 link: 源码)。
    // 若一律按"内置 = 跳过"处理,这些插件源码虽进了 bundle 却不会被安装,换机后凭空消失。
    // 真正的官方内置组合包从不在 profile 的 dependencies 里,"依赖表里查不到"才是可靠判据。
    install: (p.bundles || []).map((name) => {
      const dep = (p.deps || []).find((d) => d.name === name)
      if (dep && dep.kind === 'link') {
        return {
          name,
          kind: 'link',
          vendored: Boolean(dep.inBundle),
          // 运行时按平台拼路径,避免导出机与目标机分隔符不同。
          parts: ['plugins', dep.name],
        }
      }
      if (dep) return { name, kind: dep.kind, spec: dep.spec }
      if (String(name).startsWith('@deepseek-ai/')) return { name, kind: 'builtin' }
      return { name, kind: 'unknown' }
    }),
  }))
  const home = [
    m.settingsEncrypted
      ? { kind: 'encrypted-settings', src: 'settings.enc', dest: 'settings.yaml' }
      : { kind: 'file', src: 'settings.yaml', dest: 'settings.yaml' },
  ]
  if (m.includesCredentials) {
    home.push(m.credentialsEncrypted
      ? { kind: 'encrypted-credentials', src: '.credentials.enc', dest: '.credentials.yaml', secret: true }
      : { kind: 'file', src: '.credentials.yaml', dest: '.credentials.yaml', secret: true })
  }
  return { home, profiles }
}

function helperKind(kind) {
  return kind === 'encrypted-settings' ? 'settings' : 'credentials'
}

/* ─────────────────────────────── PowerShell ─────────────────────────────── */

export function buildApplyPs1(m) {
  const plan = buildApplyPlan(m)
  const L = []
  const p = (s) => L.push(s)

  p('# Generated by dsh-sync. Review before running. Self-contained: needs only dsh + node + pnpm.')
  p('param(')
  p('  [string]$TargetHome,')
  p('  [switch]$SkipSettings,')
  p('  [switch]$SkipPlugins,')
  p('  [string[]]$Only = @(),')
  p('  [switch]$WhatIf,')
  p('  [switch]$Force')
  p(')')
  p('$ErrorActionPreference = "Stop"')
  p('$Bundle = $PSScriptRoot')
  p('# 必须显式按 UTF-8 读:PS 5.1 的 Get-Content 会用 ANSI 解码,manifest 里的中文会被解坏,')
  p('# 连带把 JSON 结构弄崩(GBK 次字节会吃掉转义反斜杠)。')
  p('$manifest = $null')
  p('try {')
  p('  $json = [System.IO.File]::ReadAllText("$PSScriptRoot\\manifest.json", [System.Text.Encoding]::UTF8)')
  p('  $manifest = $json | ConvertFrom-Json')
  p('} catch {')
  p('  Write-Host "warning: manifest.json unreadable - skipping the version compatibility check" -ForegroundColor Yellow')
  p('}')
  p('$Helper = Join-Path $Bundle "tools\\dsync-helper.mjs"')
  p('$TargetHome = if ($TargetHome) { $TargetHome } elseif ($env:DSH_HOME) { $env:DSH_HOME } else { "$env:USERPROFILE\\.dsh" }')
  p('$Stamp = Get-Date -Format yyyyMMdd-HHmmss')
  p('$BackupDir = Join-Path $TargetHome ".dsh-sync-backup-$Stamp"')
  p('$BackedUp = New-Object System.Collections.Generic.List[string]')
  p('')
  p('function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }')
  p('function Backup-File($target) {')
  p('  if (-not (Test-Path $target)) { return }')
  p('  $rel = $target.Substring($TargetHome.Length).TrimStart("\\", "/")')
  p('  $dst = Join-Path $BackupDir $rel')
  p('  New-Item -ItemType Directory -Path (Split-Path $dst) -Force | Out-Null')
  p('  Copy-Item $target $dst -Force')
  p('  $BackedUp.Add($target) | Out-Null')
  p('}')
  p('function Restore-All {')
  p('  if ($BackedUp.Count -eq 0) { return }')
  p('  Write-Host "!! rolling back $($BackedUp.Count) file(s)" -ForegroundColor Yellow')
  p('  foreach ($t in $BackedUp) {')
  p('    $rel = $t.Substring($TargetHome.Length).TrimStart("\\", "/")')
  p('    $src = Join-Path $BackupDir $rel')
  p('    if (Test-Path $src) { Copy-Item $src $t -Force; Write-Host "   restored $rel" }')
  p('  }')
  p('}')
  p('')
  p('Write-Host "== dsh-sync apply ==" -ForegroundColor Cyan')
  p('Write-Host "bundle : $Bundle"')
  p('Write-Host "target : $TargetHome"')
  p('')
  p('# 0) 传输可能损坏/截断:在覆盖主机配置之前先整包校验,坏了就停手。')
  p('Write-Step "verifying bundle integrity"')
  p('& node $Helper verify')
  p('if ($LASTEXITCODE -ne 0) { throw "bundle integrity check failed; refusing to apply" }')
  p('')
  p('# 起飞前检查:缺什么就在动手之前讲清楚。跑到一半才发现 "dsh 不是命令" 最浪费时间,')
  p('# 那时配置已被改了一半 —— 虽然能回滚,但不如一开始就别开始。')
  p('if (-not (Get-Command node -ErrorAction SilentlyContinue)) {')
  p('  throw "node is required (it runs the integrity check and the decryption helper)"')
  p('}')
  p('$haveDsh = [bool](Get-Command dsh -ErrorAction SilentlyContinue)')
  p('if (-not $haveDsh -and -not $SkipPlugins) {')
  p('  throw "dsh is not on PATH. Install dsh first (it owns the dsh plugin add step), or rerun with -SkipPlugins to restore only settings/credentials and install plugins later."')
  p('}')
  p('if ($haveDsh -and -not (Get-Command pnpm -ErrorAction SilentlyContinue)) {')
  p('  Write-Host "warning: pnpm not found - dsh plugin add will likely fail installing dependencies" -ForegroundColor Yellow')
  p('}')
  p('')
  p('# 版本兼容预警:装完才发现版本对不上、起来就崩,是最糟糕的失败方式。')
  p('if ($haveDsh -and $manifest -and $manifest.source -and $manifest.source.dshVersion) {')
  p('  $srcVer = $manifest.source.dshVersion')
  p('  $curVer = (& dsh --version 2>$null | Out-String).Trim()')
  p('  if ($curVer -and ($curVer -notmatch [regex]::Escape($srcVer))) {')
  p('    Write-Host "warning: 源机 dsh $srcVer / 本机 $curVer —— 版本不一致" -ForegroundColor Yellow')
  p('    Write-Host "         继续可能会因配置格式差异启动异常,建议先把两机 dsh 版本对齐。" -ForegroundColor Yellow')
  p('  }')
  p('}')
  p('')
  p('# 覆盖确认:目标目录已经有一份配置时,必须先问过人再动手。')
  p('if (-not $WhatIf -and -not $Force -and (Test-Path (Join-Path $TargetHome "settings.yaml"))) {')
  p('  Write-Host ""')
  p('  Write-Host "目标目录里已经有一份 dsh 配置: $TargetHome" -ForegroundColor Yellow')
  p('  Write-Host "继续会覆盖它,旧文件会先备份到 .dsh-sync-backup-<时间戳>。"')
  p('  $ans = Read-Host "确定继续请输入 yes,其它任意输入取消"')
  p('  if ($ans -ne "yes") {')
  p('    Write-Host "已取消,没有做任何改动。" -ForegroundColor Yellow')
  p('    exit 0   # 用户主动取消不是失败:别走回滚分支,也别给非零退出码')
  p('  }')
  p('}')
  p('')
  p('# 1) 预演:只打印计划,不碰目标机任何文件。')
  p('if ($WhatIf) {')
  p('  Write-Host "-- dry run, nothing will be changed --" -ForegroundColor Yellow')
  if (plan.home.length) {
    p('  Write-Host "[home]"')
    for (const h of plan.home) p(`  Write-Host "  copy ${h.src} -> ${h.dest}"`)
  }
  for (const prof of plan.profiles) {
    p(`  Write-Host "[profile ${prof.name}]"`)
    for (const f of prof.profileFiles) p(`  Write-Host "  file ${f}"`)
    for (const ins of prof.install) {
      const note = ins.kind === 'builtin' ? 'skip  (builtin)'
        : ins.kind === 'unknown' ? 'skip  (not in deps)'
          : (ins.kind === 'link' && !ins.vendored) ? 'skip  (not vendored)'
            : 'add  '
      p(`  Write-Host "  ${note} ${ins.name}"`)
    }
  }
  p('  return')
  p('}')
  p('')
  p('try {')
  p('  if (-not (Test-Path $TargetHome)) { New-Item -ItemType Directory -Path $TargetHome -Force | Out-Null }')
  p('')
  p('  if (-not $SkipSettings) {')
  p('    Write-Step "restoring home-level declaration"')
  for (const h of plan.home) {
    p(`    if (Test-Path "$Bundle\\${h.src}") {`)
    p(`      $dest = Join-Path $TargetHome "${h.dest}"`)
    p('      Backup-File $dest')
    if (h.kind === 'file') {
      p(`      Copy-Item "$Bundle\\${h.src}" $dest -Force`)
      p(`      Write-Host "   ${h.dest}${h.secret ? ' (contains secrets)' : ''}"`)
    } else {
      p(`      & node $Helper decrypt --kind ${helperKind(h.kind)} --out $dest`)
      p(`      if ($LASTEXITCODE -ne 0) { throw "decrypt failed for ${h.src} (wrong passphrase?)" }`)
      p(`      Write-Host "   ${h.dest} (decrypted)"`)
    }
    p('    }')
  }
  p('  } else { Write-Host "skip settings (-SkipSettings)" -ForegroundColor DarkGray }')
  p('')
  p('  # profile 声明文件必须在 plugin add 之前落地,否则 pnpm 读不到 allowBuilds / registry 等配置。')
  for (const prof of plan.profiles) {
    p(`  Write-Step "profile ${prof.name}: declaration files"`)
    p(`  $profDir = Join-Path $TargetHome "profiles\\${prof.name}"`)
    p('  if (-not (Test-Path $profDir)) { New-Item -ItemType Directory -Path $profDir -Force | Out-Null }')
    for (const f of prof.profileFiles) {
      p(`  if (Test-Path "$Bundle\\profiles\\${prof.name}\\${f}") {`)
      p(`    Backup-File (Join-Path $profDir "${f}")`)
      p(`    Copy-Item "$Bundle\\profiles\\${prof.name}\\${f}" (Join-Path $profDir "${f}") -Force`)
      p(`    Write-Host "   ${f}"`)
      p('  }')
    }
  }
  p('')
  p('  if (-not $SkipPlugins) {')
  for (const prof of plan.profiles) {
    p(`    Write-Step "profile ${prof.name}: installing bundles"`)
    for (const ins of prof.install) {
      if (ins.kind === 'builtin') {
        p(`    # ${ins.name}: dsh 内置组合包,安装自带,重复 add 无意义`)
        continue
      }
      if (ins.kind === 'unknown') {
        p(`    Write-Host "skip ${ins.name}: in bundles but missing from dependencies" -ForegroundColor DarkGray`)
        continue
      }
      if (ins.kind === 'link' && !ins.vendored) {
        p(`    Write-Host "skip ${ins.name}: link source was not vendored" -ForegroundColor Yellow`)
        continue
      }
      p(`    if ($Only.Count -gt 0 -and -not ($Only -contains "${ins.name}")) {`)
      p(`      Write-Host "skip ${ins.name}: not in -Only" -ForegroundColor DarkGray`)
      p('    } else {')
      if (ins.kind === 'link') {
        const src = '$Bundle' + ins.parts.map((x) => `\\${x}`).join('')
        p(`      if (-not (Test-Path "${src}")) { throw "missing vendored plugin: ${ins.name}" }`)
        p(`      Write-Host "dsh plugin --profile ${prof.name} add ${ins.name} (local source)"`)
        p(`      dsh plugin --profile ${prof.name} add "${src}"`)
      } else {
        p(`      Write-Host "dsh plugin --profile ${prof.name} add ${ins.spec}"`)
        p(`      dsh plugin --profile ${prof.name} add ${JSON.stringify(ins.spec)}`)
      }
      p(`      if ($LASTEXITCODE -ne 0) { throw "dsh plugin add failed for ${ins.name}" }`)
      p('    }')
    }
  }
  p('  } else { Write-Host "skip plugin install (-SkipPlugins)" -ForegroundColor DarkGray }')
  p('}')
  p('catch {')
  p('  Write-Host ""')
  p('  Write-Host "APPLY FAILED: $($_.Exception.Message)" -ForegroundColor Red')
  p('  Restore-All')
  p('  Write-Host "Your previous configuration was restored from $BackupDir" -ForegroundColor Yellow')
  p('  exit 1')
  p('}')
  p('')
  p('Write-Host ""')
  p('Write-Host "Done. Restart dsh to load the migrated configuration." -ForegroundColor Green')
  p('if (Test-Path $BackupDir) { Write-Host "Previous files: $BackupDir" -ForegroundColor DarkGray }')
  if (m.includesCredentials) {
    p('Write-Host "This bundle carried credentials - delete every copy of it now." -ForegroundColor Yellow')
  }
  for (const item of (m.notMigrated || [])) {
    p(`Write-Host "note: ${item.summary}" -ForegroundColor DarkGray`)
  }
  // PowerShell 5.1 按 ANSI 解析无 BOM 的脚本,中文会显示成乱码;加回 BOM 才能在老机器上正常读。
  return '﻿' + L.join('\r\n') + '\r\n'
}

/* ─────────────────────── Windows 一键恢复向导(.bat) ─────────────────────── */

/**
 * 傻瓜式入口:新机上双击即走完全流程。
 * 存在的理由是现实约束 —— 目标机常常连 dsh 都还没装,指望用户记 CLI 参数不现实。
 * 所以这里用纯批处理兜住:先体检、先验货、先给计划,最后才动手。
 * 注意:内容以 UTF-8 写出,首行自行 `chcp 65001`,避免中文在 GBK 控制台变乱码。
 */
export function buildApplyBat(m) {
  const L = []
  const p = (s) => L.push(s)

  p('@echo off')
  p('chcp 65001 >nul 2>&1')
  p('cd /d "%~dp0"')
  p('title dsh 配置一键恢复')
  p('')
  p('echo.')
  p('echo ============================================')
  p('echo    dsh 配置一键恢复')
  p('echo ============================================')
  p('echo.')
  p('echo   本脚本把旧电脑上的 dsh 配置装到这台电脑上。')
  p('echo   动手之前会先给你看一遍将要做什么,确认后才执行。')
  p('echo   现在关掉窗口可以随时取消,不会有任何改动。')
  p('echo.')
  p('pause')
  p('')
  p('echo.')
  p('echo [1/6] 检查这台电脑的环境...')
  p('where node >nul 2>nul')
  p('if errorlevel 1 goto :nonode')
  p('echo      [OK]  Node.js 已安装')
  p('goto :checkdsh')
  p('')
  p(':nonode')
  p('echo      [缺]  Node.js —— 请先到 https://nodejs.org 安装 22 或更高版本,')
  p('echo             装好后重新双击本脚本。')
  p('goto :die')
  p('')
  p(':checkdsh')
  p('where dsh >nul 2>nul')
  p('if errorlevel 1 goto :nodsh')
  p('echo      [OK]  dsh 已安装')
  p('set EXTRA=')
  p('goto :checkpnpm')
  p('')
  p(':nodsh')
  p('echo      [缺]  dsh —— 安装插件这一步必须有它。')
  p('echo.')
  p('echo      请选择:')
  p('echo        A   我先去装 dsh,装好了再回来双击本脚本(推荐)')
  p('echo        B   这次只恢复设置和密钥,插件等装好 dsh 后再跑一次')
  p('echo.')
  p('set /p ANS=      请输入 A 或 B 后回车:')
  p('if /i "%ANS%"=="B" goto :skipplugins')
  p('echo.')
  p('echo      那先去把 dsh 装好吧,装完重新双击本脚本即可。')
  p('goto :die')
  p('')
  p(':skipplugins')
  p('set EXTRA=-SkipPlugins')
  p('echo      好的,本次只恢复设置和密钥。')
  p('goto :choosehome')
  p('')
  p(':checkpnpm')
  p('where pnpm >nul 2>nul')
  p('if errorlevel 1 echo      [提醒] 没找到 pnpm,装插件时可能会用到它')
  p('')
  p(':choosehome')
  p('echo.')
  p('echo [2/6] 恢复到哪个目录?')
  p('set "DSYNC_DEFAULT=%DSH_HOME%"')
  p('if "%DSYNC_DEFAULT%"=="" set "DSYNC_DEFAULT=%USERPROFILE%\\.dsh"')
  p('echo      新电脑上 dsh 的配置目录(不确定就用默认,直接回车)。')
  p('echo      默认: %DSYNC_DEFAULT%')
  p('set /p DSYNC_HOME=      目录:')
  p('if "%DSYNC_HOME%"=="" set "DSYNC_HOME=%DSYNC_DEFAULT%"')
  p('echo      将恢复到: %DSYNC_HOME%')
  p('')
  p(':verify')
  p('echo.')
  p('echo [3/6] 检查迁移包有没有在拷贝过程中损坏...')
  p('node "%~dp0tools\\dsync-helper.mjs" verify')
  p('if errorlevel 1 goto :badbundle')
  p('goto :plan')
  p('')
  p(':badbundle')
  p('echo.')
  p('echo      包不完整或被改过,请不要继续 —— 重新拷贝一次整个文件夹。')
  p('goto :die')
  p('')
  p(':plan')
  p('echo.')
  p('echo [4/6] 下面是将要做的改动(到这里为止还没动过你任何文件):')
  p('echo --------------------------------------------')
  p('powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0apply.ps1" -TargetHome "%DSYNC_HOME%" -WhatIf %EXTRA%')
  p('echo --------------------------------------------')
  p('echo.')
  p('set /p GO=      确认执行就输入 Y 再回车,其它任意输入取消:')
  p('if /i not "%GO%"=="Y" goto :cancel')
  p('')
  p('set EXTRA_APPLY=%EXTRA%')
  p('echo.')
  p('echo [5/6] 请输入迁移口令(旧电脑导出时给你的那串字符):')
  p('set /p SYNCKEY=      口令:')
  p('set DSH_SYNC_PASSPHRASE=%SYNCKEY%')
  p('')
  p('echo.')
  p('echo [6/6] 正在恢复,请稍候(插件多的时候要几分钟)...')
  p('powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0apply.ps1" -TargetHome "%DSYNC_HOME%" %EXTRA_APPLY%')
  p('if errorlevel 1 goto :failed')
  p('')
  p('echo.')
  p('echo ============================================')
  p('echo   恢复完成!')
  p('echo   接下来:关掉本窗口,重新启动 dsh。')
  p('echo   配置目录: %DSYNC_HOME%')
  p('echo ============================================')
  p('echo.')
  p('echo   安全提醒:配置已就位,请把这个迁移文件夹连同迁移口令一起删掉。')
  if (m.includesCredentials) {
    p('echo   (本包含密钥,别留在桌面或网盘里。)')
  }
  p('echo.')
  p('goto :die')
  p('')
  p(':failed')
  p('echo.')
  p('echo      中途出错,已经自动还原成你原来的配置了。')
  p('echo      上面红色的报错就是原因;单个插件失败时,')
  p('echo      可以双击后用 -Only 的方式只重试那一个。')
  p('goto :die')
  p('')
  p(':cancel')
  p('echo.')
  p('echo      已取消,这台电脑上的东西一个都没动。')
  p('goto :die')
  p('')
  p(':die')
  p('echo.')
  p('pause')
  return L.join('\r\n') + '\r\n'
}

/* ───────────────────────────── POSIX shell ──────────────────────────────── */

export function buildApplySh(m) {
  const plan = buildApplyPlan(m)
  const L = []
  const p = (s) => L.push(s)

  p('#!/usr/bin/env bash')
  p('# Generated by dsh-sync. Review before running. Self-contained: needs only dsh + node + pnpm.')
  p('set -euo pipefail')
  p('')
  p('TARGET_HOME="${TARGET_HOME:-${DSH_HOME:-$HOME/.dsh}}"')
  p('SKIP_SETTINGS=0; SKIP_PLUGINS=0; ONLY=""; DRY_RUN=0; FORCE=0')
  p('')
  p('usage() {')
  p('  cat <<EOF')
  p('Usage: ./apply.sh [options]')
  p('')
  p('  --home <dir>       target \$DSH_HOME (default: \$DSH_HOME or ~/.dsh)')
  p('  --skip-settings    do not touch settings.yaml / .credentials.yaml')
  p('  --skip-plugins     do not run "dsh plugin add"')
  p('  --only <a,b,c>     only install these bundles')
  p('  --dry-run          print the plan and exit')
  p('  -h, --help         show this help')
  p('EOF')
  p('}')
  p('while [ $# -gt 0 ]; do')
  p('  case "$1" in')
  p('    --home) TARGET_HOME="$2"; shift 2 ;;')
  p('    --skip-settings) SKIP_SETTINGS=1; shift ;;')
  p('    --skip-plugins) SKIP_PLUGINS=1; shift ;;')
  p('    --only) ONLY="$2"; shift 2 ;;')
  p('    --dry-run) DRY_RUN=1; shift ;;')
  p('    --force) FORCE=1; shift ;;')
  p('    -h|--help) usage; exit 0 ;;')
  p('    *) echo "unknown option: $1" >&2; usage; exit 2 ;;')
  p('  esac')
  p('done')
  p('')
  p('BUNDLE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"')
  p('HELPER="$BUNDLE/tools/dsync-helper.mjs"')
  p('BACKUP_DIR="$TARGET_HOME/.dsh-sync-backup-$(date +%Y%m%d-%H%M%S)"')
  p('RESTORED=""')
  p('')
  p('step() { printf "\\033[36m==> %s\\033[0m\\n" "$1"; }')
  p('info() { printf "   %s\\n" "$1"; }')
  p('warn() { printf "\\033[33m%s\\033[0m\\n" "$1"; }')
  p('')
  p('backup_file() {')
  p('  local t="$1" rel dest')
  p('  [ -e "$t" ] || return 0')
  p('  rel="${t#"$TARGET_HOME"/}"')
  p('  dest="$BACKUP_DIR/$rel"')
  p('  mkdir -p "$(dirname "$dest")"')
  p('  cp -p "$t" "$dest"')
  p('  RESTORED="$RESTORED $t"')
  p('}')
  p('restore_all() {')
  p('  [ -n "$RESTORED" ] || return 0')
  p('  warn "!! rolling back"')
  p('  for t in $RESTORED; do')
  p('    rel="${t#"$TARGET_HOME"/}"')
  p('    if [ -e "$BACKUP_DIR/$rel" ]; then cp -p "$BACKUP_DIR/$rel" "$t"; info "restored $rel"; fi')
  p('  done')
  p('}')
  p('on_error() { printf "\\033[31mAPPLY FAILED\\033[0m (line $1)\\n" >&2; restore_all; exit 1; }')
  p("trap 'on_error $LINENO' ERR")
  p('')
  p('wanted() { [ -z "$ONLY" ] && return 0; case ",$ONLY," in *",$1,"*) return 0 ;; *) return 1 ;; esac; }')
  p('')
  p('echo "== dsh-sync apply =="')
  p('echo "bundle : $BUNDLE"')
  p('echo "target : $TARGET_HOME"')
  p('')
  p('step "verifying bundle integrity"')
  p('node "$HELPER" verify || { echo "integrity check failed; refusing to apply" >&2; exit 1; }')
  p('')
  p("# 起飞前检查:缺什么就在动手之前讲清楚,避免装到一半才发现 'dsh: command not found'。")
  p('command -v node >/dev/null 2>&1 || { echo "node is required (integrity check + decryption helper)" >&2; exit 1; }')
  p('if ! command -v dsh >/dev/null 2>&1; then')
  p('  if [ "$SKIP_PLUGINS" -eq 0 ]; then')
  p('    echo "dsh is not on PATH. Install dsh first (it owns the dsh plugin add step), or rerun with --skip-plugins to restore only settings/credentials." >&2')
  p('    exit 1')
  p('  fi')
  p('  warn "dsh not found - plugin installation will be skipped"')
  p('fi')
  p('command -v pnpm >/dev/null 2>&1 || warn "pnpm not found - dsh plugin add may fail installing dependencies"')
  p('')
  p('# 版本兼容预警:装完才发现版本对不上、起来就崩,是最糟糕的失败方式。')
  p('src_ver=$(node -p "try{(require(\'$BUNDLE/manifest.json\').source||{}).dshVersion||\'\'}catch(e){\'\'}" 2>/dev/null)')
  p('if [ -n "$src_ver" ] && command -v dsh >/dev/null 2>&1; then')
  p('  cur_ver=$(dsh --version 2>/dev/null | head -1)')
  p('  case "$cur_ver" in')
  p('    *"$src_ver"*) ;;')
  p('    *) warn "版本不一致: 源机 dsh $src_ver / 本机 $cur_ver —— 建议先对齐版本再继续" ;;')
  p('  esac')
  p('fi')
  p('')
  p('# 覆盖确认:目标已有一份配置时,先问过人再动手。')
  p('if [ -f "$TARGET_HOME/settings.yaml" ] && [ "$FORCE" -eq 0 ] && [ "$DRY_RUN" -eq 0 ]; then')
  p('  echo ""')
  p('  warn "目标目录里已经有一份 dsh 配置: $TARGET_HOME"')
  p('  echo "   继续会覆盖它,旧文件会先备份到 .dsh-sync-backup-<时间戳>。"')
  p('  printf "   确定继续请输入 yes,其它任意输入取消: "')
  p('  read -r answer')
  p('  [ "$answer" = "yes" ] || { echo "已取消,没有做任何改动。"; exit 0; }')
  p('fi')
  p('')
  p('if [ "$DRY_RUN" -eq 1 ]; then')
  p('  warn "-- dry run, nothing will be changed --"')
  if (plan.home.length) {
    p('  echo "[home]"')
    for (const h of plan.home) p(`  info "copy ${h.src} -> ${h.dest}"`)
  }
  for (const prof of plan.profiles) {
    p(`  echo "[profile ${prof.name}]"`)
    for (const f of prof.profileFiles) p(`  info "file ${f}"`)
    for (const ins of prof.install) {
      const note = ins.kind === 'builtin' ? 'skip (builtin)'
        : ins.kind === 'unknown' ? 'skip (not in deps)'
          : (ins.kind === 'link' && !ins.vendored) ? 'skip (not vendored)'
            : 'add '
      p(`  info "${note} ${ins.name}"`)
    }
  }
  p('  exit 0')
  p('fi')
  p('')
  p('mkdir -p "$TARGET_HOME"')
  p('')
  p('if [ "$SKIP_SETTINGS" -eq 0 ]; then')
  p('  step "restoring home-level declaration"')
  for (const h of plan.home) {
    p(`  if [ -f "$BUNDLE/${h.src}" ]; then`)
    p(`    dest="$TARGET_HOME/${h.dest}"`)
    p('    backup_file "$dest"')
    if (h.kind === 'file') {
      p(`    cp -p "$BUNDLE/${h.src}" "$dest"`)
      p(`    info "${h.dest}${h.secret ? ' (contains secrets)' : ''}"`)
    } else {
      p(`    node "$HELPER" decrypt --kind ${helperKind(h.kind)} --out "$dest" \\`)
      p(`      || { echo "decrypt failed for ${h.src} (wrong passphrase?)" >&2; exit 1; }`)
      p(`    info "${h.dest} (decrypted)"`)
      p('    chmod 600 "$dest" 2>/dev/null || true')
    }
    p('  fi')
  }
  p('else')
  p('  warn "skip settings (--skip-settings)"')
  p('fi')
  p('')
  for (const prof of plan.profiles) {
    p(`step "profile ${prof.name}: declaration files"`)
    p(`prof_dir="$TARGET_HOME/profiles/${prof.name}"`)
    p('mkdir -p "$prof_dir"')
    for (const f of prof.profileFiles) {
      p(`if [ -f "$BUNDLE/profiles/${prof.name}/${f}" ]; then`)
      p(`  backup_file "$prof_dir/${f}"`)
      p(`  cp -p "$BUNDLE/profiles/${prof.name}/${f}" "$prof_dir/${f}"`)
      p(`  info "${f}"`)
      p('fi')
    }
  }
  p('')
  p('if [ "$SKIP_PLUGINS" -eq 0 ]; then')
  for (const prof of plan.profiles) {
    p(`  step "profile ${prof.name}: installing bundles"`)
    for (const ins of prof.install) {
      if (ins.kind === 'builtin') {
        p(`  # ${ins.name}: builtin bundle shipped with dsh itself`)
        continue
      }
      if (ins.kind === 'unknown') {
        p(`  warn "skip ${ins.name}: in bundles but missing from dependencies"`)
        continue
      }
      if (ins.kind === 'link' && !ins.vendored) {
        p(`  warn "skip ${ins.name}: link source was not vendored"`)
        continue
      }
      p(`  if wanted "${ins.name}"; then`)
      if (ins.kind === 'link') {
        const src = '"$BUNDLE/' + ins.parts.join('/') + '"'
        p(`    [ -d ${src} ] || { echo "missing vendored plugin: ${ins.name}" >&2; exit 1; }`)
        p(`    echo "dsh plugin --profile ${prof.name} add ${ins.name} (local source)"`)
        p(`    dsh plugin --profile ${prof.name} add ${src}`)
      } else {
        p(`    echo "dsh plugin --profile ${prof.name} add ${ins.spec}"`)
        p(`    dsh plugin --profile ${prof.name} add ${JSON.stringify(ins.spec)}`)
      }
      p('  else')
      p(`    info "skip ${ins.name} (not in --only)"`)
      p('  fi')
    }
  }
  p('else')
  p('  warn "skip plugin install (--skip-plugins)"')
  p('fi')
  p('')
  p('printf "\\033[32mDone.\\033[0m Restart dsh to load the migrated configuration.\\n"')
  p('[ -d "$BACKUP_DIR" ] && echo "Previous files: $BACKUP_DIR"')
  if (m.includesCredentials) {
    p('warn "This bundle carried credentials - delete every copy of it now."')
  }
  for (const item of (m.notMigrated || [])) {
    p(`echo "note: ${item.summary}"`)
  }
  return L.join('\n') + '\n'
}
